# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('voter_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('middleName', models.CharField(blank=True, max_length=40)),
                ('lastName', models.CharField(max_length=50)),
                ('suffix', models.CharField(blank=True, max_length=5)),
                ('telephoneNum', models.CharField(blank=True, max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('dateOfBirth', models.CharField(max_length=8)),
                ('resStreetAddress1', models.TextField()),
                ('resStreetAddress2', models.TextField(blank=True)),
                ('resCity', models.TextField()),
                ('resCounty', models.TextField()),
                ('resState', models.TextField()),
                ('resZip', models.CharField(max_length=5)),
                ('mailStreetAddress1', models.TextField()),
                ('mailStreetAddress2', models.TextField(blank=True)),
                ('mailCity', models.TextField()),
                ('mailState', models.TextField()),
                ('mailZip', models.CharField(max_length=5)),
                ('ssn', models.CharField(max_length=9)),
                ('driversLicense', models.CharField(blank=True, max_length=20)),
                ('citizenshipDocType', models.TextField()),
                ('politicalParty', models.TextField()),
                ('voterStatus', models.TextField()),
                ('absenteeApply', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
