# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='voter_id',
            field=models.TextField(default='Not Generated', primary_key=True, serialize=False),
        ),
    ]
