# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateOfBirth',
            field=models.CharField(max_length=100),
        ),
    ]
