# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171112_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='citizenshipDocument',
            field=models.ImageField(default='documentation/none/no-img.jpg', upload_to='documentation/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='middleName',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
