# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171203_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biometricsDocument',
            field=models.TextField(default='BiometricsDocument'),
        ),
        migrations.AlterField(
            model_name='user',
            name='citizenshipDocument',
            field=models.TextField(default='CitizenDocument'),
        ),
    ]
