# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171116_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenshipDocument', models.CharField(max_length=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='citizenshipDocument',
        ),
        migrations.AddField(
            model_name='userdocs',
            name='voter_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
    ]
