# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171117_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdocs',
            name='voter_id',
        ),
        migrations.DeleteModel(
            name='UserDocs',
        ),
    ]
