# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171119_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='citizenshipDocument',
            field=models.ImageField(default='documentation/none/no-img.jpg', upload_to='documentation/'),
        ),
    ]
