# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_citizenshipdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='citizenshipDocument',
            field=models.TextField(),
        ),
    ]
