# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171124_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biometricsDocument',
            field=models.CharField(default='BiometricsDocument', max_length=150000),
        ),
        migrations.AlterField(
            model_name='user',
            name='citizenshipDocument',
            field=models.CharField(default='CitizenDocument', max_length=150000),
        ),
    ]
